# Packages

We've seen how functions make it easy to write general-purpose routines that we can reuse, saving us from rewriting the code. You can imagine that there are a vast number of functions that might be useful for our coding purposes. Some of these are implemented for us in default Python. Things like addition, writing to files, appending elements to lists, are functions that someone wrote and made accessible to you when you launch the Python executable. However, despite the large set of functions packaged with Python by default, there are many possibly useful functions that are not. We wouldn't want the Python install to be a terrabyte, after all. 

Since Python doesn't include all the functions we want, we can always just write what we need ourselves. But writing software, especially efficient, reliable, and complicated software, is time consuming and requires a lot of background knowledge. It might even require writing in other programming languages.

For example, we might want a function that takes 2 lists and creates an image showing the data plotted as pairs of coordinates on a set of axes. We could spend weeks or months toiling away trying to write our own function to do this, or we could just let someone else do it and copy their function (with their permission of course). That was the beauty of functions after all, they're portable code blocks that aren't tied to any specific use-case/program. This is where packages come in.

Python packages are essentially libraries of functions written by others and kindly distributed to us for free. So how does it work? Well, first we need to download and install these fancy libraries. Then we simply load them into our environment and we're free to use them to our heart's content. It's as easy as that. 

## Some Noteworthy Packages:
1. NumPy: Elaborate suite of math and array functions. Maybe the most common package in Python
2. SciPy: Extensive set of useful scientific functions useful for statistics, math, and more
3. Matplotlib: An excellent package for creating custom plots and data visualizations
4. Pandas: A data analysis package built around implementing DataFrame objects
5. AstroPy: A utility package for all things astronomy

Note that even these packages use packages! In fact, #2-5 are all built on top of NumPy!

There's genuinely nothing special about the code contained in packages. You could write it yourself given enough time. They just save us from re-doing things other people already did, allowing us to focus on the fun science. It also helps maintain interoperability. Many packages work seamlessly together because they are both built on NumPy. You can imagine how complicated things would get if everyone did everything their own way.

## Let's import a package

Before running the next cell, ensure that you have NumPy installed. If you're using a conda distribution of Python, go to the terminal, activate your desired environment and run 'conda install numpy'. If that fail or you are not using conda, go to a terminal and run 'pip install numpy'.

Remember, packages are libraries *external* to Python. We have to download and install them in order to use them. We'll talk more about package managers at the end of this notebook, but you've been reading for a while already so let's run some code!

In [ ]:
# To load a package for use in your program, simply use the 'import' keyword 
#  followed by the name of the package
import numpy

Now that we've loaded in NumPy, we have access to tons of new functions. Suppose NumPy contains a function with the same name as a built-in function, though (it does). How can Python know which one to use? 

By default, Python will make a packages functions accessible via the '.' syntax on the package name. So to access the 'add' function from NumPy, we would write 'numpy.add()' rather than simply add(), even though there is no default Python function names add(). 

In [ ]:
# This runs the add function implemented in NumPy
print(numpy.add(1,2))

# Python has a sum() function built in for adding all the numbers in a list
print(sum([1,2,3]))

# NumPy also has a sum() function which can do the same thing
print(numpy.sum([1,2,3]))

#Note that the two functions achieve the same result, but they are actually running different code.

Sometimes package names are long, so it can get annoying writing them every time we want to use one of their functions. Luckily, Python has aliasing built-in to allow us to use whatever name we want to reference a package. 

This can make your code less readable, so many packages have standard abbreviations that almost everyone uses. This makes it easier to understand what someone else's code does without having to think too hard.

In [ ]:
# Let's import NumPy with an alias
# Simply use the 'as' keyword (just like we did with file I/O)
import numpy as np

# Now 'np' will be interpreted as numpy and can be used in its place
np.add(1,2)

# Note Python will not recognize the original name if we alias it
# That means that in this case, if we load numpy as np, we can no longer 
#  write something like numpy.add(), we have to use the np alias.


Like we said, NumPy is a very large library of functions. That means loading them all into memory may be laborious for certain applications. Or we may have other libraries that are extremely bloated. If this is the case, and we only need 1 or 2 functions, Python allows us to import only specific functions from within libraries by using the 'from' keyword.

In [ ]:
# If we only want to import the add() function, we just use this call
from numpy import add

# Now we can use add() without the numpy.add syntax
add(1,2)

In [ ]:
# We could also alias just the function
from numpy import add as addition

addition(1,2)

In [ ]:
# If we import a function that is already defined, the new function takes precedence
sum?

In [ ]:
from numpy import sum
sum?

Ok, so packages have a ton of useful functions, and there are tons of useful packages. How can you find what packages to use and what functions they contain?

### Good ol' Google

On of the first things you can do when you're stuck in your programming or you feel like there must be a better way is to simply Google how to do a particular thing. The internet is bursting with info on coding, and the most popular packages have been used and reused in almost every way imagineable. You would be hard-pressed to encounter an issue that someone else hasn't already had and solved.

### Documentation

Any package that is meant to be useful to others will have some sort of online documentation. Most packages have their documented source code publicly available on GitHub. Larger packages like NumPy and AstroPy have dedicated sites for hosting extensive documentation, examples, and troubleshooting. 

This can be daunting as the packages generally have a lot of functions, but if you hone in on specific functions at first, you'll see that the documentation is no harder to read than the doc strings we have already worked with. Also, you can usually scroll down to see examples that you can even copy-paste to run/modify just to get a feel for the usage. 


# Challenge

Go to one of the documentation sites below and find a function you like or think would be useful. Read over the docs for that function and how to use it, and come to the next class ready to briefly present the function to the class.

NumPy: https://numpy.org/doc/stable/

SciPy: https://docs.scipy.org/doc/scipy/

## Extras

If you spend some time on the docs for NumPy or similar packages, you'll find that the functions are often catagorized under certain banners. These are submodules contained within one pacakge. For example, in SciPy has a stats module, a linalg module, an optimize module, etc. To import or access submodules or their functions, we need to use the '.' syntax again.

In [ ]:
# Suppose I want to use SciPy's curve fitting function
# Since it is in the optimize submodule, I need to tell Python to look there for it

import scipy
scipy.optimize.curve_fit

In [ ]:
# Alternatively, I can import just the submodule or just the function itself as before
import scipy.optimize
scipy.optimize.curve_fit

In [ ]:
from scipy.optimize import curve_fit
curve_fit

In [ ]:
from scipy import optimize
optimize.curve_fit

While the above are all valid ways of loading the curve_fit() function, it is good to consider readability and reliability when writing code. Importing the function directly as curve_fit() may be less typing, but since it could overwrite other functions/variables in the namespace, it is often better to use the dotted namespace to alieviate possible confusion.

In [15]:
#Solution using Lists

#when working with lists we would need to go through each and every element and multiply it by 2
number_list = [1, 4, 6, 10, 40, 100]

#for loop that goes through the index values of the number_list list
for i in range(len(number_list)):
    
    #We replace the current value at index i with the value multiplied by 2
    number_list[i] = number_list[i] * 2

print(number_list)

[2, 8, 12, 20, 80, 200]


In [17]:
#With arrays it is as simple as multiplying the array by 2
number_list = [1, 4, 6, 10, 40, 100]

#To do this we simply convert the list to an array using np.array()
num_arr = np.array(number_list)

#then multiply the array by 2
print(2*num_arr)

#Wow!!! Super easy and no need for for-loops :D!!!

[  5  11  15  23  83 203]


This same ease can be acquired through all the other mathematical functions such as division, adding, subtracting, raising to a power

In [18]:
#division

#with one line we can divide the ENTIRE array by 2
num_arr/2

array([ 0.5,  2. ,  3. ,  5. , 20. , 50. ])

In [19]:
#adding

#with one line we can add the ENTIRE array by 2
num_arr + 2

array([  3,   6,   8,  12,  42, 102])

In [20]:
#subtracting

#with one line we can subtract the ENTIRE array by 2
num_arr - 2

array([-1,  2,  4,  8, 38, 98])

In [21]:

#with one line we can square the ENTIRE array
num_arr**2

array([    1,    16,    36,   100,  1600, 10000])

## Exercise

Make your own numpy array and do the following: 

- a) multiply the array by 3
- b) divide the array by 100
- c) compute the line equation 3*x + 5 where x is your array

In [22]:
########## Code Here ###########

#making an array
arr = np.array([23, 54, 67, 90, -102, 234, -202, 356, -10394, 324])

#a)
print(arr*3)

#b)
print(arr/100)

#c)
print(3*arr+5)

[    69    162    201    270   -306    702   -606   1068 -31182    972]
[   0.23    0.54    0.67    0.9    -1.02    2.34   -2.02    3.56 -103.94
    3.24]
[    74    167    206    275   -301    707   -601   1073 -31177    977]


# Array math between multiple arrays

The way that array math works between 2 or more arrays is by doing element wise arithmetic. The entries at the same location undergo the operation being performed. So if you have 2 arrays with 3 numbers in them say arr1 = np.array([1, 5, 10]) and arr2 = np.array([10, 20, 30]) when you do an operation say addition. This operation is applied to the same indexes so 1 will get added to 10, 5 will get added to 20 and 10 will get added to 30 making the resulting array be np.array([11, 25, 40]). This same methodology is applied if you add another array into the mix where similar indexes have the operation applied to them. See the example below of this in action.


NOTE: The array $\textbf{must}$ be the same shape and size for this to work. If you have an array that is shorter or longer then you will get an error.

In [23]:
arr1 = np.arange(1, 11, 1)
arr2 = np.arange(21, 31, 1)
arr3 = np.arange(101, 111, 1)

In [24]:
print(arr1)
print(arr2)
print(arr3)

[ 1  2  3  4  5  6  7  8  9 10]
[21 22 23 24 25 26 27 28 29 30]
[101 102 103 104 105 106 107 108 109 110]


In [25]:
arr1+arr2

array([22, 24, 26, 28, 30, 32, 34, 36, 38, 40])

In [26]:
arr1+arr2+arr3

array([123, 126, 129, 132, 135, 138, 141, 144, 147, 150])

In [27]:
arr1*arr2

array([ 21,  44,  69,  96, 125, 156, 189, 224, 261, 300])

In [28]:
arr1*arr2*arr3

array([ 2121,  4488,  7107,  9984, 13125, 16536, 20223, 24192, 28449,
       33000])

In [29]:
arr1/arr2

array([0.04761905, 0.09090909, 0.13043478, 0.16666667, 0.2       ,
       0.23076923, 0.25925926, 0.28571429, 0.31034483, 0.33333333])

In [30]:
arr1/arr2/arr3

array([0.00047148, 0.00089127, 0.00126636, 0.00160256, 0.00190476,
       0.00217707, 0.00242298, 0.0026455 , 0.0028472 , 0.0030303 ])

In [31]:
arr1-arr2

array([-20, -20, -20, -20, -20, -20, -20, -20, -20, -20])

In [32]:
arr1-arr2-arr3

array([-121, -122, -123, -124, -125, -126, -127, -128, -129, -130])

In [33]:
arr2//arr1

array([21, 11,  7,  6,  5,  4,  3,  3,  3,  3])

In [34]:
arr2%arr1

array([0, 0, 2, 0, 0, 2, 6, 4, 2, 0])

# Generating Arrays

Numpy has many built in functions that allows you to quickly get a large array between a starting and ending number. Some of those functions are np.linspace(), np.arange(), np.logspace(). These functions are really great when we need to generate an array of X-values for our plots. We will cover all three of them in detail in the next few cells. 

In short np.linspace() produces an array that is equally spaced between a starting and ending number

np.arange() has a step size argument so you can give np.arange() a starting and ending point and a step size and you will get an array of values separated by the step size you inputted. This is really good when you are doing histograms as you have full control over the bin size through the step_size argument in np.arange()


np.logspace() is similar to np.linspace() but it generates a set of equally spaced values from starting number to ending number in log-space. 

In [38]:
#quickly generating an array of 1000 equally spaced values between 1-100
#Note how the ending number 100 is included
x = np.linspace(-100, 100, 500)
print(len(x))

500


In [39]:
#quickly generating an array of 10 equally spaced values between 1-100
np.linspace(1, 100, 10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [45]:
#let us try to create the same array as above but with np.arange
np.arange(1, 100, 1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [41]:
#np.arange is exclusive of the ending number so if we want it to end at 100 we need to increase the ending number
np.arange(1, 101, 11)

array([  1,  12,  23,  34,  45,  56,  67,  78,  89, 100])

In [49]:
#np.logspace works in logspace and the starting and ending values are the log of those numbers
#so a value of -2 is the same as 10^-2, a value of 4 is 10^4, value of 0 is 10^0 = 1
#this genereates an equal spacing array in log-space which is different than linear spacing
np.logspace(0, 2, 100)

array([  1.        ,   1.04761575,   1.09749877,   1.149757  ,
         1.20450354,   1.26185688,   1.32194115,   1.38488637,
         1.45082878,   1.51991108,   1.59228279,   1.66810054,
         1.7475284 ,   1.83073828,   1.91791026,   2.009233  ,
         2.10490414,   2.20513074,   2.3101297 ,   2.42012826,
         2.53536449,   2.65608778,   2.7825594 ,   2.91505306,
         3.05385551,   3.19926714,   3.35160265,   3.51119173,
         3.67837977,   3.85352859,   4.03701726,   4.22924287,
         4.43062146,   4.64158883,   4.86260158,   5.09413801,
         5.33669923,   5.59081018,   5.85702082,   6.13590727,
         6.42807312,   6.73415066,   7.05480231,   7.39072203,
         7.74263683,   8.11130831,   8.49753436,   8.90215085,
         9.32603347,   9.77009957,  10.23531022,  10.72267222,
        11.23324033,  11.76811952,  12.32846739,  12.91549665,
        13.53047775,  14.17474163,  14.84968262,  15.55676144,
        16.29750835,  17.07352647,  17.88649529,  18.73

# Exercise 

Using linspace, logspace or building your own arrays make 5 arrays of length 10 of:

- Mass1 Array: An array of masses in units of kg, should be between $10^{29} - 10^{34}$ kgs
- Mass2 Array: An array of masses in units of kg, should be between $10^{32} - 10^{34}$ kgs
- Distance Array: An array of distances in meters of order $10^{10} - 10^{30}$ m
- Radius1 Array: An array of raidus in meters of order $10^{7} - 10^{10}$ m
- Radius2 Array: An array of raidus in meters of order $10^{7} - 10^{10}$ m


Once you have created the arrays please do the following: 

1. Compute the gravitational attraction between the two Stars in Mass1 and Mass2 using:

$F = \frac{G m_1 m_2}{d^2}$

2. Compute the escape velocity of each of the stars:

$v_{esc} = \sqrt{\frac{2 G M}{R}}$


3. Compute the average of the Mass, Radius and Distance



In [55]:
########## Code Here ###########

Mass1 = np.linspace(1e29, 1e34, 10)
#Mass1 = np.logspace(29, 34, 10)

Mass2 = np.linspace(1e32, 1e34, 10)
#Mass2 = np.logspace(32, 34, 10)

distance = np.linspace(1e10, 1e30, 10)
#distance = np.logspace(10, 34, 10)

Radius1 = np.linspace(1e7, 1e10, 10)
Radius2 = np.linspace(1e7, 1e10, 10)

G = 6.67e-11

Force = (G*Mass1*Mass2)/distance**2
vesc1 = (2*G*Mass1/Radius1)**(1/2)
vesc2 = (2*G*Mass2/Radius2)**(1/2)

#vesc1 = np.sqrt(2*G*Mass1/Radius1

avg_Mass1 = np.sum(Mass1)/Mass1.shape

In [52]:
Mass1.shape

(10,)

In [54]:
avg_Mass1

5.00005e+33

# Useful Numpy Functions

In [56]:
example_array = np.array([-10, -9, -30, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 
                           -134, 332, 324, -3312, 23213, -423321, 12321])

In [60]:
positive_mask = example_array > 0

In [61]:
example_array[positive_mask]

array([    1,     2,     3,     4,     5,     6,     7,     8,     9,
          10,   332,   324, 23213, 12321])

In [58]:
idx = np.where(example_array > 0)

In [59]:
example_array[idx]

array([    1,     2,     3,     4,     5,     6,     7,     8,     9,
          10,   332,   324, 23213, 12321])

In [62]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [63]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

# Boolean Masking

A very cool thing that arrays can do is that we can perform conditional expressions across an entire array. This will result in an array of True and False values which we can use to subselect the relevant values from a larger array. Let us see this in action below.

In [ ]:
random_numbers = np.random.normal(loc = 2, scale = 1, size = 100)

print(random_numbers)
print()
print('Length: ', len(random_numbers))

In [ ]:
#making a conditional to only select numbers between 2 and 4
range_2_to_4 = ((random_numbers > 2) &
                (random_numbers < 4))

print(range_2_to_4)

In [ ]:
#let us now apply this boolean mask to the random numbers to subselect the values within the range 2 to 4

subsample = random_numbers[range_2_to_4]

print(subsample)
print()
print('Length: ', len(subsample))

# Note:

Boolean masks are a great way to subselect data from an array with ease but it does come at a cost in that when you apply the mask onto an array it alters the size of the array, we started off with an array of length 100 and when we applied the mask it down selected reducing the size of the array. This has important implication if you are working with many different arrays and they need to be the same size for plotting. The way to fix this is that you would need to apply this mask to the other arrays as well to make sure they are the same size and match up for any subsequent analysis and plotting purposes.

# 2D Arrays

In the next few notebooks, we will encounter a type of array called ND-Arrays these arrays are N-dimensional arrays but for the sake of introducing ND-arrays we will be working with 2D-arrays but the same concepts learned here can be extrapolated to higher dimensional arrays. 2D arrays are the typical data structure of images which will be the focus of the Photometry Module. So knowing how to manipulate 2D arrays and performing mathematical operations is crucial for that module. 

2D arrays are made by turning a list of list into an array. Take, for example. that we have the following list within list [[1, 2, 3, 4], [10, 11, 12, 13]], we can turn this into a 2D array using the np.array() function.

    twoD_array = np.array([[1, 2, 3, 4], [10, 11, 12, 13]])
    
What numpy will do is that it will make the first list, [1, 2, 3, 4], be the first row in the 2D array and the second list, [10, 11, 12, 13], will be the second row. This will make a matrix with row and column values. With this example shown here it will make a 2x4 array with 2 rows and 4 columns. Let us apply this in python.

In [ ]:
#defining a 2D array with 2 rows and 4 columns
twoD_array = np.array([[1, 2, 3, 4],[10, 11, 12, 13]])

print(twoD_array)

# Indexing 2D Arrays

Indexing 2D-arrays builds on indexing 1D arrays as we have two locations to specify we need to specify. The index across the row and the index across the column to grab the value that we want. Let us say we want to get the value 12. By eye we can see that it is in the second row and in the third column. All the rules of indexing still apply as well as splicing, striding and negative indexing. In this simple example of getting 12 we would do the following:

In [ ]:
#getting the value of 12, 2nd row is index 1 and 3rd column is at index 2
twoD_array[1, 2]

In general to get a single value from a 2D array requires us to use the syntax below:

twoD_array[Row_index, Column_index]


This can be generalized to include slicing:

twoD_array[start_row_index:ending_row_index, start_col_index: ending_col_index]

Note that the ',' is what tells python when the index is for row or for columns

If you want all the rows of a column the syntax for that is as follows:

twoD_array[:, col_index]

If you want all the columns from a row you can use either of the two methods shown below:

1. twoD_array[row_index]
2. twoD_array[row_index, :]

Both will give you the entire row corresponding to the row_index. 

Let's apply this to a larger 2D array to see this in action.

In [ ]:
big_2d_arr = np.random.normal(loc = 2, 
                              scale = 1, 
                              size = (10, 12), #this is how you tell numpy you want a 10x12 array of values
                              )

print(big_2d_arr)

In [ ]:
#let's select the entire 5th row
print(big_2d_arr[4])
print('or')
print(big_2d_arr[4, :])

In [ ]:
#let's select the entire 5th column
print(big_2d_arr[:, 4])

In [ ]:
#let us select row 2 - 5 and columns 6 - 10

    #row indexing , column indexing
big_2d_arr[1:5    ,  5:10]

# Math with 2D Arrays and Scalars

Everything we covered with 1D arrays for scalar arithmetic stills applies with 2D array you can take any number and perform any math operator on a 2D-array and every single element will have that operation applied.


In [ ]:
twod_arr = np.ones(shape = (4, 5))
print(twod_arr)

In [ ]:
twod_arr + 5

In [ ]:
twod_arr - .5

In [ ]:
twod_arr / 2

In [ ]:
twod_arr * 5

In [ ]:
(2*twod_arr)**2

# Math between 2D Arrays and 1D Arrays

You can also perform mathematical operators between 2D arrays and 1D arrays but there is a criteria that must be met, the 1D array $\textbf{MUST}$ be the same size as the columns of the 2D array. So if you have a 10 x 12 array the 1D array needs to be length 12 to perform mathematical operations. 

The way math is carried out between these two is that every row gets the math operator applied making sure that the same elements are undergoing the operation. To explain this with an example let us take the following array: np.array([[1, 2, 3], [2, 4, 8], [3, 6, 9]]) and the 1D-array np.array([2, 2, 2]) and let's say I need to multiply these two arrays. 

What will happen is that numpy will take the first row of the 2D array and perform the multiplication [1, 2, 3] * [2, 2, 2] and since we have two 1D arrays of the same length we perform the operation element-wise. The output for this is going to be: [2, 4, 6] and this will be the new row1 in the output 2D array. The second row then does the same operation: [2, 4, 8] * [2, 2, 2] = [4, 8, 16] and this will be the second row and so on. so the resulting 2D array from this operation will be: np.array([[2, 4, 6], [4, 8, 16], [6, 12, 18]]). 


In [ ]:
ex_2darr = np.array([[1, 2, 3], [2, 4, 8], [3, 6, 9]])
ex_1darr = np.array([2, 2, 2])

In [ ]:
ex_2darr + ex_1darr

In [ ]:
ex_2darr - ex_1darr

In [ ]:
ex_2darr * ex_1darr

In [ ]:
ex_2darr / ex_1darr

# Math Between 2D Arrays and 2D Arrays

You can also perform mathematical operations between many other 2D arrays. This also has a strict criteria that must be met and this is that the $\textbf{shape}$ of the arrays $\textbf{MUST}$ be the same. The number of rows and columns must match exactly for mathematical operations to be performed between any number of 2D arrays. The math performed here is done element wise so every item with a similar row and column index will have the operation applied to it. The first row and first column element of all the arrays will have the math operation performed, The first row and second column element of all the arrays will have the math operation performed, and so on. Let's see an example of this in use.

In [ ]:
twod_arr1 = np.random.randint(1, 100, size = (5, 7))
twod_arr2 = np.random.random(size = (5, 7))

In [ ]:
#you can check the shape of an array using the shape attribute
twod_arr1.shape

In [ ]:
#you can check the shape of an array using the shape attribute
twod_arr2.shape

In [ ]:
twod_arr1 + twod_arr2

In [ ]:
twod_arr1 - twod_arr2

In [ ]:
twod_arr1 * twod_arr2

In [ ]:
twod_arr1 / twod_arr2

# Boolean Masking for 2D Arrays

Everything we covered about masking for 1D array is transferable to 2D arrays. We just have an added dimension to work with. The main thing to note about applying boolean masks to 2D arrays is that it changes both the row and column size based off of the mask being applied.

In [ ]:
ex_2d_arr = np.random.normal(loc = 2, scale = 1, size = (5, 7))

ex_2d_arr > 3

In [ ]:
bool_mask = ex_2d_arr > 3

ex_2d_arr_masked = ex_2d_arr[bool_mask]

print(ex_2d_arr_masked)

In [ ]:
#you can apply a 1D boolean mask so long as it matches the row or column length you are trying to mask

#this will mask out the 2nd and last row of the 2D array
bool_mask1d = np.array([True, False, True, True, False])

print(ex_2d_arr[bool_mask1d])
print()
print(ex_2d_arr[bool_mask1d].shape)

In [ ]:
#you can apply a 1D boolean mask so long as it matches the row or column length you are trying to mask

#this will mask out the 2nd and 5th columns of the 2D array
bool_mask1d = np.array([True, False, True, True, False, True, True])

print(ex_2d_arr[:, bool_mask1d])
print()
print(ex_2d_arr[:, bool_mask1d].shape)